BROKER = "localhost:9092"

TRANSACTIONS_TOPIC = "transactions"

DEFAULT_PARTITIONS = 3

DEFAULT_REPLICATION_FACTOR = 1

DEFAULT_TRANSACTIONS_PER_SECOND = 100

DEFAULT_TRANSACTION_COUNT = 1000

DEFAULT_FRAUD_RATIO = 0.05

DEFAULT_NUMBER_OF_CARDS = 10

DEFAULT_AMOUNT_DISTRIBUTION = "uniform"

ACKS = "all"

RETRIES = 5

ENABLE_IDEMPOTENCE = True

CONSUMER_GROUP = "fraud_detection_group"
